account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('register/', views.Register.as_view(), name='register'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('profile/', views.UserProfile.as_view(), name='profile'),
    path('phone_register/<str:uidb64>/<str:token>/', views.PhoneRegister.as_view(), name='phone_register'),
    path('register/email_active/<str:uidb64>/<str:token>/', views.Register.as_view(), name='email_active'),
    path('user_profile_update/', views.user_profile_update, name='user_profile_update'),
    path('ticket_send/', views.ticket_send, name='ticket_send'),
    # mobile verify
    # path('send_code/', views.SendCode.as_view(), name='send_code'),
    path('send_code/', views.send_code, name='send_code'),
    path('verify_code/', views.VerifyCode.as_view(), name='verify_code'),
    # upload_document_url
    path('id_card_upload/', views.id_card_upload, name='id_card_upload'),
    path('bank_card_upload/', views.bank_card_upload, name='bank_card_upload'),
    path('profile_image_upload/', views.profile_image_upload, name='profile_image_upload'),
    # reset password
    path('password_reset_1/', views.ResetPassword.as_view(), name='password_reset_1'),
    path('password_reset_2/<str:uidb64>/<str:token>/', views.ResetPasswordConfirm.as_view(), name='password_reset_2'),
    # notify read
    path('notification_read/', views.ReadNotification.as_view()),

    path('get_admin_inform/', views.admin_page_information)
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('buy_order/', views.Buy.as_view(), name='buy_order'),
    path('sell_order/', views.Sell.as_view(), name='sell_order'),
    path('order_buy_show/<int:order_id>/', views.BuyShow.as_view(), name='order-buy-show'),
    path('order_sell_show/', views.SellShow.as_view(), name='order_sell_show'),
    path('form_buy_sell/', views.FormBuySell.as_view(), name='form_buy_sell'),

]

pm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from azbankgateways.urls import az_bank_gateways_urls
from account.views import callback_gateway_view, go_to_gateway_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('ticket/', include('ticket.urls', namespace='ticket')),
    path('', include('product.urls', namespace='product')),
    path('order/', include('order.urls', namespace='order')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('api/', include('api.urls', namespace='api')),
    # third_apps
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # payment
    path('bankgateways/', az_bank_gateways_urls()),
    path('payment/<int:order_id>/', go_to_gateway_view, name='payment'),
    path('callback-gateway/<int:order_id>/', callback_gateway_view, name='callback-gateway'),
    # end payment

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                        document_root=settings.
                                                                                        MEDIA_ROOT)

order/models.py
from django.db import models
from account.models import User


class ConditionChoices(models.TextChoices):
    accept = 'accept'
    reject = 'reject'
    pending = 'pending'
    null = 'null'


class OrderBuy(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    dollar_price = models.IntegerField()
    quantity = models.IntegerField()
    paid = models.BooleanField(default=False)
    tracking_code = models.CharField(max_length=300, null=True, blank=True)
    condition = models.CharField(max_length=255, choices=ConditionChoices.choices, default=ConditionChoices.null)

    def __str__(self):
        return self.user.username

    @property
    def total_price(self):
        p = self.dollar_price * self.quantity
        return p


class OrderSell(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    voucher_code = models.CharField(max_length=60)
    activate_code = models.CharField(max_length=60)
    paid = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

order/forms.py
from django import forms
from .models import OrderBuy, OrderSell


class BuyForm(forms.ModelForm):
    class Meta:
        model = OrderBuy
        fields = ['quantity']


class SellForm(forms.ModelForm):
    class Meta:
        model = OrderSell
        fields = ['voucher_code', 'activate_code']

order/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.views import View
from account.models import Profile
from api.models import DollarPriceModel
from .forms import *


class Buy(View):
    def post(self, request):
        profile_user = Profile.objects.get(user_id=request.user.id)
        inventory = profile_user.buy_sum
        if inventory <= 9000000 and profile_user.vip_user is False or inventory > 9000000 and profile_user.vip_user:
            form = BuyForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                order_obj = OrderBuy.objects.create(user_id=request.user.id,
                                                    dollar_price=DollarPriceModel.objects.get().price,
                                                    quantity=cd['quantity'])
                order_obj.save()
                messages.success(request, 'سفارش شما ثبت شد لطفا جهت نهایی شدن, اقدام به پرداخت کنید.')
                order = OrderBuy.objects.get(id=order_obj.id)
                order_id = order.id
                return render(request, 'order/order_buy.html', {'order': order, 'order_id': order_id})
            else:
                messages.error(request, 'متاسفانه خاطایی رخ داده است !است لطفا دوباره تلاش کنید.')
                return redirect(request.META.get('HTTP_REFERER'))
        else:
            messages.error(request, 'سقف مجاز شما به حد نصاب خود رسیده لطفا اقدام به احراز هویت کنید')
            return redirect(request.META.get('HTTP_REFERER'))


class Sell(View):
    def post(self, request):
        form = SellForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            order_obj = OrderSell.objects.create(user_id=request.user.id, voucher_code=cd['voucher_code'],
                                                 activate_code=cd['activate_code'])
            order_obj.save()
            messages.success(request, 'سفارش شما با موفقیت ثبت شد در کمترین زمان ممکن به حساب شما واریز خواهد شد')
            return redirect('order:order_sell_show')
        else:
            messages.error(request, 'متاسفانه خاطایی رخ داده است ! لطفا دوباره امتحان کنید.')
            return redirect(request.META.get('HTTP_REFERER'))


class BuyShow(View):
    def get(self, request, order_id):
        pass


class SellShow(View):
    def get(self, request):
        buy_obj = OrderSell.objects.filter(user_id=request.user.id)
        paginator = Paginator(buy_obj, 2)
        page = request.GET.get('page')
        page_obj = paginator.get_page(page)
        return render(request, 'order/order_sell.html', {'order': page_obj, 'page_num': page})


class FormBuySell(View):
    def get(self, request):
        dollar_price = DollarPriceModel.objects.get().price
        form_buy = BuyForm()
        form_sell = SellForm()
        context = {'form_buy': form_buy, 'form_sell': form_sell, 'dollar_price': dollar_price}
        return render(request, 'order/form_exchange.html', context)

order/templates/order/failed_buy.html
{% extends 'base_profile.html' %}
{% load static %}
{% block third_css %}
    <link rel="stylesheet" href="{% static 'account/css/p.css' %}">
{% endblock %}
{% block body %}
<div class="container py-4 mt-5">
        <div class="card shadow">
            <div class="card-body">
                <div class="row">
                    <div class="col-12">
                        <div class="text-center">
                            <span class="fw-bold text-danger">پرداخت ناموفق</span>
                        </div>
                        <div class="col-12 mt-4">
                            <div class="text-center">
                                کد پیگیری: <span>{{ tc }}</span>
                            </div>
                        </div>
                        <div class="col-12 mt-4">
                            <div class="text-center">
                                پرداخت شما ناموفق بود. در صورت کسر وجه مبلغ کسر شده طی مدت 42 ساعت به حساب شما برمیگردد
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="text-center">
                                <a href="{% url 'account:profile' %}" style="text-decoration-line: none;">
                                    <button type="button" class="btn btn-success mt-4">رفتن به داشبورد</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

order/templates/order/form_exchange.html
{% extends 'base_profile.html' %}
{% load static %}
{% block third_css %}
    <link rel="stylesheet" href="{% static 'account/css/profile.css' %}">
    <style>
        #d-buysell .card {
            width: 400px;
            background-color: #fff;
            border: none;
            border-radius: 12px
        }

        #d-buysell label.radio {
            cursor: pointer;
            width: 100%
        }

        #d-buysell label.radio input {
            position: absolute;
            top: 0;
            left: 0;
            visibility: hidden;
            pointer-events: none
        }

        #d-buysell label.radio span {
            padding: 7px 14px;
            border: 2px solid #eee;
            display: inline-block;
            color: #039be5;
            border-radius: 10px;
            width: 100%;
            height: 48px;
            line-height: 30px
        }

        #d-buysell label.radio input:checked + span {
            border-color: #039BE5;
            background-color: #81D4FA;
            color: #fff;
            border-radius: 9px;
            height: 48px;
            line-height: 30px
        }

        #d-buysell .form-control {
            margin-top: 10px;
            height: 48px;
            border: 2px solid #eee;
            border-radius: 10px;
        }

        #d-buysell .form-control:focus {
            box-shadow: none;
            border: 2px solid #039BE5;
        }

        #d-buysell .agree-text {
            font-size: 12px;
        }

        #d-buysell .terms {
            font-size: 12px;
            text-decoration: none;
            color: #039BE5;
        }

        #d-buysell .confirm-button {
            height: 50px;
            border-radius: 10px;
        }

        #p-h {
            margin-top: 10px;
            height: 48px;
            border: 2px solid #eee;
            border-radius: 0px 10px 10px 0px;
        }
    </style>
{% endblock %}
{% block body %}
    <div class="container mt-5 mb-5 d-flex justify-content-center">
        <div class="card px-1 py-4 shadow">
            <form method="post" action="{% url 'order:buy_order' %}" id="shop_form">
                {% csrf_token %}
                <div class="card-body ">
                    <div class="d-flex flex-row">
                        <label class="radio mr-1">
                            <input id="buy-radio" type="radio" name="add" value="anz" checked>
                            <span> <i class="fa fa-shopping-cart"></i>
                        <strong class="ms-2">خرید</strong>
                        </span>
                        </label>
                        <label class="radio">
                            <input id="sell-radio" type="radio" name="add" value="add">
                            <span> <i class="fa fa-money"></i>
                        <strong class="ms-2">فروش</strong>
                        </span>
                        </label>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <!-- <label for="name">Name</label> -->
                                <div class="input-group">
                                <span id="p-h" class="input-group-text">قیمت یک واحد ووچر</span>
                                    <input type="number" class="form-control bg-white" id="dollar-price" name="dollar_price"
                                           aria-label="Sizing example input"
                                           aria-describedby="inputGroup-sizing-sm" value="{{ dollar_price }}" readonly>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <div class="input-group"><input id="v-count" name="quantity" class="form-control"
                                                                type="number"
                                                                placeholder="تعداد ووچر" min="1" style="direction: rtl">
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <div class="input-group"><input id="code-v" name="voucher_code" class="form-control"
                                                                type="text"
                                                                placeholder="کد ووچر" style="display: none;">
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <div class="input-group"><input id="a-code" name="activate_code" class="form-control"
                                                                type="text"
                                                                placeholder="کد فعال سازی" style="display: none;">
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="row" id="total-price">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <div class="input-group">
                                    <span id="p-h" class="input-group-text" >مبلغ کل (تومان)</span>
                                    <input id="t-num" type="number" class="form-control bg-white" aria-label="Sizing example input"
                                           aria-describedby="inputGroup-sizing-sm" value="32500" readonly>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class=" d-flex flex-column text-center px-5 mt-3 mb-3"><strong class="agree-text">
                    لطفا در پر کردن فیلد ها نهایت دقت را داشته باشید</strong></div>
                <div class=" d-flex justify-content-center">
                    <button type="submit" class="btn btn-warning btn-block confirm-button">ثبت سفارش</button>
                </div>
                </div>


            </form>
        </div>
    </div>
    {% block script %}
        <script src="{% static 'order/js/form.js' %}"></script>
    {% endblock %}
{% endblock %}

order/templates/order/order_buy.html
{% extends 'base_profile.html' %}
{% load static %}
{% block third_css %}
{% endblock %}
{% block body %}
    <div style="padding-bottom: 150px; padding-top: 50px; height: 100vh; background-image: linear-gradient(to right, #6a11cb 0%, #2575fc 100%);">
        <div class="container">
            <div class="card">
                <div class="card-header text-center">
                    <span>تصویه حساب</span>
                </div>
                <div class="card-body">
                    <div>
                        <ul class="list-unstyled text-center">
                            <li class="mb-3">
                                <span>تعداد ووچر: </span><span>{{ order.quantity }}</span>
                            </li>
                            <li class="mb-3">
                                <span class="fw-bold">قیمت پایانی: </span><span class="fw-bold">{{ order.total_price }}</span><span> تومان</span>
                            </li>
                            <li class="mb-3">
                                <a href="{% url 'payment' order_id %}">
                                    <button class="btn btn-success">پرداخت</button>
                                </a>
                            </li>
                            <li class="mb-3">
                                <a href="{% url 'account:profile' %}">
                                    <button class="btn btn-danger">انصراف و بازگشت به داشبورد</button>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

order/templates/order/order_sell.html
{% extends 'base_profile.html' %}
{% load static %}
{% block third_css %}
    <link rel="stylesheet" href="{% static 'account/css/profile.css' %}">
{% endblock %}
{% block body %}
    <div class="py-4">
        <div class="container">
            <div class="card">
                <div class="card-body">
                    <table class="table table-striped" id="buy" style="display:table">
                        <thead>
                        <tr>
                            <th>ردیف</th>
                            <th>نوع</th>
                            <th>ووچر</th>
                            <th>مبلغ (تومان)</th>
                            <th>وضعیت</th>
                            <th>تصویه</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for order_items in order %}
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td>خرید</td>
                                <td>پرفکت مانی</td>
                                <td>{{ order_items.total_price }}</td>
                                <td>{% if order_items.paid == True %}
                                    <strong class="text-success">پرداخت شده</strong>{% else %}
                                    <strong class="text-success">در انتظار پرداخت</strong>{% endif %}
                                </td>
                                <td>{% if order_items.paid == False %}
                                    <a href="#" style="text-decoration-line: none"><strong>پرداخت</strong></a>
                                {% else %} <p>-</p>
                                {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <div class="d-flex justify-content-center">
                        <nav aria-label="Page navigation example" style="direction: ltr">
                            <ul class="pagination">
                                {% if order.has_previous %}
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ order.previous_page_number }}">Previous</a>
                                    </li>
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ order.previous_page_number }}">{{ order.previous_page_number }}</a>
                                    </li>
                                {% endif %}

                                <li class="page-item {% if page_num == page_num %} active{% endif %}"><a
                                        class="page-link"
                                        href="?page={{ order.number }}">{{ order.number }}</a>
                                </li>
                                {% if order.has_next %}
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ order.next_page_number }}">{{ order.next_page_number }}</a>
                                    </li>
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ order.next_page_number }}">Next</a>
                                    </li>

                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

order/templates/order/success_buy.html
{% extends 'base_profile.html' %}
{% load static %}
{% block third_css %}
{% endblock %}
{% block body %}
    <div class="container" style="padding-bottom: 150px; height: 100vh;">
        <div class="card shadow">
            <div class="card-body">
                <div class="row">
                    <div class="col-12">
                        <div class="text-center">
                            <span class="fw-bold text-success">پرداخت با موفقیت انجام شد</span>
                        </div>
                        <div class="col-12 mt-4">
                            <div class="text-center">
                                کد پیگیری: <span>{{ tc }}</span>
                            </div>
                        </div>
                        <div class="col-12 mt-4">
                            <div class="text-center">
                                کد ووچر شما ظرف مدت 10 دقیقه صادر خواهد شد و از قسمت کیف ووچر قابل مشاهده خواهد بود
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="text-center">
                                <a href="{% url 'account:profile' %}" style="text-decoration-line: none;">
                                    <button type="button" class="btn btn-success mt-4">رفتن به داشبورد</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}