pm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from azbankgateways.urls import az_bank_gateways_urls
from account.views import callback_gateway_view, go_to_gateway_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('ticket/', include('ticket.urls', namespace='ticket')),
    path('', include('product.urls', namespace='product')),
    path('order/', include('order.urls', namespace='order')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('api/', include('api.urls', namespace='api')),
    # third_apps
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # payment
    path('bankgateways/', az_bank_gateways_urls()),
    path('payment/<int:order_id>/', go_to_gateway_view, name='payment'),
    path('callback-gateway/<int:order_id>/', callback_gateway_view, name='callback-gateway'),
    # end payment

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                        document_root=settings.
                                                                                        MEDIA_ROOT)

ticket/urls.py
from django.urls import path
from . import views

app_name = 'ticket'

urlpatterns = [
    path('ticket/<int:ticket_id>/', views.SingleTicketView.as_view(), name='single_ticket'),
    path('ticket_show/', views.TicketShow.as_view(), name='ticket_show'),
    path('ticket_form/', views.TicketFormView.as_view(), name='ticket_formView'),
]

ticket/models.py
from django.db import models
from account.models import User


class TicketStatus(models.TextChoices):
    TO_DO = 'To Do'
    DONE = 'Done'


class Ticket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    status = models.CharField(max_length=255, choices=TicketStatus.choices, default=TicketStatus.TO_DO)
    body = models.TextField()
    created_at = models.DateTimeField('created at', auto_now_add=True)
    updated_at = models.DateTimeField('updated at', auto_now=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.created_at = self.updated_at
        super(Ticket, self).save(*args, **kwargs)


class ReplyTicket(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, related_name='rep')
    rep_body = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.ticket.title)

ticket/forms.py
from django import forms
from .models import Ticket


class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['title', 'body']

ticket/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import TicketForm
from .models import Ticket
from django.core.paginator import Paginator
from django.contrib import messages


class SingleTicketView(View):
    single_ticket_template = 'ticket/single_show.html'

    def get(self, request, ticket_id):
        ticket_obj = Ticket.objects.get(id=ticket_id)
        context = {'ticket': ticket_obj}
        return render(request, self.single_ticket_template, context)


class TicketShow(View):
    def get(self, request):
        buy_obj = Ticket.objects.filter(user_id=request.user.id)
        paginator = Paginator(buy_obj, 2)
        page = request.GET.get('page')
        page_obj = paginator.get_page(page)
        return render(request, 'ticket/ticket.html', {'ticket': page_obj, 'page_num': page})


class TicketFormView(View):
    ticket_form = TicketForm

    def get(self, request):
        form = self.ticket_form()
        context = {'form': form}
        return render(request, 'ticket/ticket_form.html', context)

    def post(self, request):
        form = self.ticket_form(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            ticket_obj = Ticket.objects.create(user_id=request.user.id, title=cd['title'], body=cd['body'])
            ticket_obj.save()
            messages.success(request, 'تیکت شما با موفقیت ارسال شد , منتظر پاسخگویی تیم پشتیبانی باشید')
            return redirect('ticket:ticket_show')
        else:
            messages.error(request, 'ارسال تیکت با مشکل مواجه شد, لطفا دوباره امتحان کنید')
            return redirect('ticket:ticket_formView')

ticket/templates/ticket/single_show.html
{% extends 'base_profile.html' %}
{% load static %}
{% block third_css %}
    <link rel="stylesheet" href="{% static 'account/css/profile.css' %}">
{% endblock %}
{% block body %}
    <div class="container py-4 d-flex justify-content-center">
        <div class="card" style="width: 18rem;">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">{{ ticket.body }}</li>
                <li class="list-group-item">{{ ticket.reply }}</li>
            </ul>
            <div class="card-footer">
                Card footer
            </div>
        </div>

    </div>
{% endblock %}

ticket/templates/ticket/ticket.html
{% extends 'base_profile.html' %}
{% load static %}
{% block third_css %}
    <link rel="stylesheet" href="{% static 'account/css/profile.css' %}">
{% endblock %}
{% block body %}
    <div class="py-4">
        <div class="container">
            <div class="card">
                <div class="card-body">
                    <table class="table table-hover text-center">
                        <thead>
                        <tr>
                            <th scope="col">ردیف</th>
                            <th scope="col">تیکت</th>
                            <th scope="col">وضعیت</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for tickets in ticket %}
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td>
                                    {% if tickets.status == 'Done' %}
                                        <a class="text-truncate" href="{% url 'ticket:single_ticket' tickets.id %}"
                                           style="text-decoration-line: none;">{{ tickets.body }}</a>
                                    {% else %}
                                        <p class="text-truncate">{{ tickets.body }}</p>
                                    {% endif %}
                                </td>
                                <td>{% if tickets.status == 'To Do' %}
                                    <span class="badge bg-info"><strong>در حال پاسخگویی</strong></span>
                                {% elif tickets.status == 'Done' %}
                                    <span class="badge bg-success"><strong>پاسخ داده شد</strong></span>
                                {% endif %}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <div class="d-flex justify-content-center">
                        <nav aria-label="Page navigation example" style="direction: ltr">
                            <ul class="pagination">
                                {% if ticket.has_previous %}
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ ticket.previous_page_number }}">Previous</a>
                                    </li>
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ ticket.previous_page_number }}">{{ ticket.previous_page_number }}</a>
                                    </li>
                                {% endif %}

                                <li class="page-item {% if page_num == page_num %} active{% endif %}"><a
                                        class="page-link"
                                        href="?page={{ ticket.number }}">{{ ticket.number }}</a>
                                </li>
                                {% if ticket.has_next %}
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ ticket.next_page_number }}">{{ ticket.next_page_number }}</a>
                                    </li>
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ ticket.next_page_number }}">Next</a>
                                    </li>

                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

ticket/templates/ticket/ticket_form.html
{% extends 'base_profile.html' %}
{% load static %}
{% block third_css %}
    <link rel="stylesheet" href="{% static 'account/css/profile.css' %}">
{% endblock %}
{% block body %}
    <div class="container py-4">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label">موضوع</label>
                        <input type="text" class="form-control" name="title" id="exampleFormControlInput1"
                               placeholder="موضوع تیکت"
                               style="direction: rtl">
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlTextarea1" class="form-label">متن تیکت</label>
                        <textarea class="form-control" name="body" id="exampleFormControlTextarea1" rows="8"></textarea>
                    </div>
                    <div class="mb-3">
                        <button type="submit" class="btn btn-warning" style="border-radius: 15px;">ثبت تیکت</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}