account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('register/', views.Register.as_view(), name='register'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('profile/', views.UserProfile.as_view(), name='profile'),
    path('phone_register/<str:uidb64>/<str:token>/', views.PhoneRegister.as_view(), name='phone_register'),
    path('register/email_active/<str:uidb64>/<str:token>/', views.Register.as_view(), name='email_active'),
    path('user_profile_update/', views.user_profile_update, name='user_profile_update'),
    path('ticket_send/', views.ticket_send, name='ticket_send'),
    # mobile verify
    # path('send_code/', views.SendCode.as_view(), name='send_code'),
    path('send_code/', views.send_code, name='send_code'),
    path('verify_code/', views.VerifyCode.as_view(), name='verify_code'),
    # upload_document_url
    path('id_card_upload/', views.id_card_upload, name='id_card_upload'),
    path('bank_card_upload/', views.bank_card_upload, name='bank_card_upload'),
    path('profile_image_upload/', views.profile_image_upload, name='profile_image_upload'),
    # reset password
    path('password_reset_1/', views.ResetPassword.as_view(), name='password_reset_1'),
    path('password_reset_2/<str:uidb64>/<str:token>/', views.ResetPasswordConfirm.as_view(), name='password_reset_2'),
    # notify read
    path('notification_read/', views.ReadNotification.as_view()),

    path('get_admin_inform/', views.admin_page_information)
]

pm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from azbankgateways.urls import az_bank_gateways_urls
from account.views import callback_gateway_view, go_to_gateway_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('ticket/', include('ticket.urls', namespace='ticket')),
    path('', include('product.urls', namespace='product')),
    path('order/', include('order.urls', namespace='order')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('api/', include('api.urls', namespace='api')),
    # third_apps
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # payment
    path('bankgateways/', az_bank_gateways_urls()),
    path('payment/<int:order_id>/', go_to_gateway_view, name='payment'),
    path('callback-gateway/<int:order_id>/', callback_gateway_view, name='callback-gateway'),
    # end payment

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                        document_root=settings.
                                                                                        MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.home, name='home'),
    path('test/', views.test, name='test')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    {% block head %}{% endblock %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.rtl.min.css"
          integrity="sha384-DOXMLfHhQkvFFp+rWTZwVlPVqdIhpDVYT9csOnHSgWQWPX0v5MCGtjCJbY6ERspU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
          integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g=="
          crossorigin="anonymous"/>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css"
          integrity="sha512-sMXtMNL1zRzolHYKEujM2AqCLUR9F2C4/05cdbxjjLSRvMQIciEPCQZo++nk7go3BtSuK9kfa/s+a4f4i5pLkw=="
          crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap5.min.css">


    <!-- font -->
    <link href="https://v1.fontapi.ir/css/Shabnam" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
          integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>


    <style>
        html {
            margin: 0;
            padding: 0;
            height: 100% !important;
        }

        body {
            margin: 0;
            padding: 0;
            height: 100% !important;
            font-family: Shabnam;
            background-image: linear-gradient(to right, #6a11cb 0%, #2575fc 100%);
        }
    </style>

    {% block third_css %}
    {% endblock %}
</head>
<body>

{% include 'nav.html' %}
{% block body %}
{% endblock %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
        integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"
        integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw=="
        crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/particlesjs/2.2.3/particles.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
{% include 'message.html' %}

<script>
    $('.owl-carousel').owlCarousel({
        rtl: true,
        loop: true,
        margin: 10,
        nav: true,
        responsiveClass: true,
        responsive: {
            0: {
                items: 1,
                nav: false
            },
            600: {
                items: 3,
                nav: false
            },
            1000: {
                items: 4,
                nav: true,
                loop: false
            }
        }
    })
</script>
<script>
    window.onload = function () {
        Particles.init({
            selector: '.background',
            color: ['#a3a3a3'],
            maxParticles: 100,
            connectParticles: true,
            responsive: [
                {
                    breakpoint:
                        768
                    ,
                    options: {
                        maxParticles:
                            100
                        ,
                        color:
                            '#a3a3a3'
                        ,
                        connectParticles:
                            false
                    }
                }, {
                    breakpoint:
                        425
                    ,
                    options: {
                        maxParticles:
                            0
                        ,
                        connectParticles:
                            false
                    }
                }, {
                    breakpoint:
                        320
                    ,
                    options: {
                        maxParticles:
                            0
                    }
                }
            ]
        });
    };
</script>
{% block script %}{% endblock %}
{% include 'footer.html' %}
</body>
</html>

templates/base_profile.html
{% load static %}
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1"/>
    <title>
        {% block title %}

        {% endblock %}
    </title>
    {% block head %}

    {% endblock %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.rtl.min.css"
          integrity="sha384-DOXMLfHhQkvFFp+rWTZwVlPVqdIhpDVYT9csOnHSgWQWPX0v5MCGtjCJbY6ERspU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
          integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g=="
          crossorigin="anonymous"/>

    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css"
          integrity="sha512-sMXtMNL1zRzolHYKEujM2AqCLUR9F2C4/05cdbxjjLSRvMQIciEPCQZo++nk7go3BtSuK9kfa/s+a4f4i5pLkw=="
          crossorigin="anonymous"/>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
          integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>

    <link href="https://v1.fontapi.ir/css/Shabnam" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/dataTables.bootstrap5.min.css">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.9.1/chart.js"
            integrity="sha512-d6nObkPJgV791iTGuBoVC9Aa2iecqzJRE0Jiqvk85BhLHAPhWqkuBiQb1xz2jvuHNqHLYoN3ymPfpiB1o+Zgpw=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <style>
        body {
            background-color: #f5f5f5 !important;
            font-family: 'shabnam';
        }
    </style>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>

    {% block third_css %}

    {% endblock %}
</head>
<body>
{% block body %}

{% endblock %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
        integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"
        integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw=="
        crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>
<script>
    window.onload = function () {
        Particles.init({
            selector: '.background',
            color: ['#48F2E3'],
            connectParticles: true,
            responsive: [
                {
                    breakpoint:
                        768
                    ,
                    options: {
                        maxParticles:
                            200
                        ,
                        color:
                            '#48F2E3'
                        ,
                        connectParticles:
                            false
                    }
                }, {
                    breakpoint:
                        425
                    ,
                    options: {
                        maxParticles:
                            100
                        ,
                        connectParticles:
                            true
                    }
                }, {
                    breakpoint:
                        320
                    ,
                    options: {
                        maxParticles:
                            0
                    }
                }
            ]
        });
    };
</script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

{% include 'message.html' %}
{% block script %}
{% endblock %}
{% include 'footer.html' %}
</body>
</html>

templates/footer.html
<footer class="bg-dark py-4" style="position: relative;">
    <div class="container-fluid">
        <div class="container" style="position: relative;">
            <div class="card border-0 bg-light shadow" style="border-radius: 10px; top:-60px;">
                <div class="card-body d-block d-md-flex">
                    <div>
                        <h3>نیاز به راهنمایی داری؟</h3>
                        <h3 class="lead">کافیه با ما تماس بگیری</h3>

                    </div>
                    <div class="ms-auto d-md-flex align-items-center">
                        <button class="btn btn-outline-danger float-end">با ما تماس بگیر</button>
                    </div>
                </div>
            </div>
            <div class="row py-4 text-white d-flex justify-content-center">
                <div class="col-12 col-md-3">
                    <p>میانبر</p>
                    <ul>
                        <li>
                            <a class="text-white" style="text-decoration-line: none" href="{% url 'product:home' %}">صفحه اصلی</a>
                        </li>
                        <li>
                            <a class="text-white" style="text-decoration-line: none" href="{% url 'account:register' %}">ثبت نام</a>
                        </li>
                        <li>
                            <a class="text-white" style="text-decoration-line: none" href="{% url 'account:login' %}">ورود</a>
                        </li>
                        <li>
                            <a class="text-white" style="text-decoration-line: none" href="{% url 'account:profile' %}">پنل کاربری</a>
                        </li>
                    </ul>
                </div>
                <div class="col-12 col-md-3">
                    <p>خرید</p>
                    <ul>
                        <li>خرید پرفکت مانی</li>
                        <li>خرید ووچر پرفکت مانی</li>
                    </ul>
                </div>
                <div class="col-12 col-md-3">
                    <p>راه های ارتباطی</p>
                    <ul>
                        <li>ایمیل:nimajavangt@gmail.com</li>
                        <li>شماره تماس:09147242591</li>
                    </ul>
                </div>
                <div class="col-12 col-md-3">
                    <p>ما را در شبکه های اجتمایی دنبال کنید</p>
                    <ul>
                        <li>ایمیل:nimajavangt@gmail.com</li>
                        <li>شماره تماس:09147242591</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/form_errors_temp.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
{% endif %}

templates/message.html
{#{% for message in messages %}#}
{#    <div class="container">#}
{#        <div class="alert {{ message.tags }} alert-dismissible fade show">#}
{#            {{ message }}#}
{#            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>#}
{#        </div>#}
{#    </div>#}
{#{% endfor %}#}
<script>
    {% for message in messages %}
        swal({
            title: {% if message.tags == 'alert-success' %}'موقق'{% elif message.tags == 'alert-danger' %}'ناموفق'{% endif %},
            text: '{{ message }}',
            icon: {% if message.tags == 'alert-success' %} 'success' {% elif message.tags == 'alert-danger' %} 'error' {% endif %},
            button: "متوجه شدم"
        });
    {% endfor %}
</script>

templates/nav.html
<div class="sticky-top p-2" style="--bs-bg-opacity: 0.90;" id="nav_bar">
    <nav class="navbar navbar-expand-lg container">
        <div class="container-fluid ">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <i class="bi bi-list text-white"></i>

            </button>
            <div class="collapse navbar-collapse d-lg-flex align-items-center justify-content-between" id="navbarSupportedContent">
                <ul class="navbar-nav d-none d-lg-flex">
                    <li class="nav-item">
                        <h3 class="text-white">Mashti Pay</h3>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item pe-4">
                        <a class="nav-link active" aria-current="page" href=""><strong class="text-white">صفحه
                            اصلی</strong></a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item pe-4">
                            <a class="nav-link"
                               href="{% url 'account:profile' %}"><strong
                                    class="{% if user.is_authenticated %} active text-warning {% else %} disabled{% endif %}">پنل
                                کاربری</strong></a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link disabled pe-4"><strong class="text-white">پروفایل کاربری</strong></a>
                        </li>
                    {% endif %}
                    <li class="nav-item pe-4">
                        <a class="nav-link" href="#"><strong class="text-white">وبلاگ</strong></a>
                    </li>
                    <li class="nav-item pe-4">
                        <a class="nav-link" href="#"><strong class="text-white">درباره ما</strong></a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    {% if not user.is_authenticated %}
                        <li>
                            <a class="nav-link" href="{% url 'account:login' %}"><strong
                                    class="text-white">ورود</strong></a>
                        </li>
                    {% elif user.is_authenticated %}
                        <li>
                            <a class="nav-link" href="{% url 'account:logout' %}"><strong
                                    class="text-white">خروج</strong></a>
                        </li>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <li>
                            <a class="nav-link disabled" href="{% url 'account:register' %}"><strong
                                    class="text-white">عضویت</strong></a>
                        </li>
                    {% elif not user.is_authenticated %}
                        <li>
                            <a class="nav-link" href="{% url 'account:register' %}"><strong
                                    class="text-white">عضویت</strong></a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</div>

<script>
    window.onscroll = function () {
        scrollFunction()
    };

    function scrollFunction() {
        if (document.body.scrollTop > 80 || document.documentElement.scrollTop > 80) {
            document.getElementById('nav_bar').style.backgroundColor = '#182747';
        } else {
            document.getElementById('nav_bar').style.backgroundColor = '';
        }
    }
</script>